spring:
  application:
    name: api-gateway
---
server:
  port: 8080
---
zuul:
  prefix: /api
  routes:
    customer:
      path: /customer/**
      serviceId: customer
    order:
      path: /order/**
      serviceId: order
---
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true