---
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///in28Minutes/git/spring-micro-services/03.microservices/git-localconfig-repo
  application:
    name: config-server
---
server:
  port: 8888